[package]
name = "zigbee2mqtt-updater"
version = "0.1.0"
authors = ["Daniel Welch <dwelch2102@gmail.com>"]

[dependencies]
serde = "1.0.63"
serde_json = "1.0.18"
serde_derive = "1.0.63"
actix-web = "0.6.10"
actix = "0.5.7"
reqwest = "0.8.5"
hyper = "0.11.27"
rust-crypto = "0.2.36"
